apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management-app-dev
spec:
  project: management
  source:
    repoURL: https://github.com/techsterr/ops-lab.git
    targetRevision: main
    path: how-to-deploy-argocd/argo-config/deployment/overlay/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
