apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  project: $(PROJECT_NAME)
  source:
    repoURL: https://github.com/techsterr/ops-lab.git
    targetRevision: HEAD
    path: $(SOURCE_PATH)/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
